# -*- Mode: makefile -*-
# SPDX-License-Identifier: GPL-2.0-or-later
# MC68030 PMMU opcode-driven system tests.

M68K_SYSTEM_TESTS_DIR := $(SRC_PATH)/tests/tcg/m68k/system

.PHONY: run-pmove
run-pmove:
	$(call run-test, $@, \
		env QEMU_M68K_SYSTEM='$(QEMU)' \
		M68K_AS='$(AS)' M68K_LD='$(LD)' \
		$(M68K_SYSTEM_TESTS_DIR)/run-pmove.sh)

EXTRA_RUNS += run-pmove

.PHONY: run-pmmu-control
run-pmmu-control:
	$(call run-test, $@, \
		env QEMU_M68K_SYSTEM='$(QEMU)' \
		M68K_AS='$(AS)' M68K_LD='$(LD)' \
		$(M68K_SYSTEM_TESTS_DIR)/run-pmmu-control.sh)

EXTRA_RUNS += run-pmmu-control

.PHONY: run-pmmu-fault-restart
run-pmmu-fault-restart:
	$(call run-test, $@, \
		env QEMU_M68K_SYSTEM='$(QEMU)' \
		M68K_AS='$(AS)' M68K_LD='$(LD)' \
		$(M68K_SYSTEM_TESTS_DIR)/run-pmmu-fault-restart.sh)

EXTRA_RUNS += run-pmmu-fault-restart

.PHONY: run-pmmu-access-frame-rte
run-pmmu-access-frame-rte:
	$(call run-test, $@, \
		env QEMU_M68K_SYSTEM='$(QEMU)' \
		M68K_AS='$(AS)' M68K_LD='$(LD)' \
		$(M68K_SYSTEM_TESTS_DIR)/run-pmmu-access-frame-rte.sh)

EXTRA_RUNS += run-pmmu-access-frame-rte

.PHONY: run-fpu-030-state
run-fpu-030-state:
	$(call run-test, $@, \
		env QEMU_M68K_SYSTEM='$(QEMU)' \
		M68K_AS='$(AS)' M68K_LD='$(LD)' \
		$(M68K_SYSTEM_TESTS_DIR)/run-fpu-030-state.sh)

EXTRA_RUNS += run-fpu-030-state
