/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Golden values were independently checked from the preserved Second Edition
 * sources in the Plan 9 rootfs: sys/src/libauth/{passtokey,convTR2M,
 * convM2TR,convT2M,convM2T,convA2M}.c and sys/man/2/encrypt.  The historical
 * DES block values
 * were cross-checked with OpenSSL DES/ECB after applying the documented
 * packed 56-bit-to-odd-parity 64-bit conversion; no real credential occurs
 * in these fixtures.
 */
#include "qemu/osdep.h"
#include "qemu/bswap.h"
#include "hw/9pfs/plan9-auth.h"
#include "qapi/error.h"

static void assert_zeroed(const void *data, size_t len);

typedef struct KeydbFixtureRecord {
    const char *name;
    uint8_t key[PLAN9_AUTH_DES_KEY_LEN];
    uint8_t status;
    uint8_t warnings;
    uint32_t expiry;
} KeydbFixtureRecord;

static const uint8_t keydb_master_key[PLAN9_AUTH_DES_KEY_LEN] = {
    0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
};

static char *keydb_tempdir(void)
{
    GError *error = NULL;
    char *dir = g_dir_make_tmp("qemu-plan9-keydb-XXXXXX", &error);

    g_assert_no_error(error);
    g_assert_nonnull(dir);
    return dir;
}

static void keydb_remove_tree(const char *dir)
{
    g_autofree char *path = g_build_filename(dir, "keys", NULL);

    unlink(path);
    rmdir(dir);
}

static void keydb_write(const char *path, const KeydbFixtureRecord *records,
                        size_t count)
{
    g_autofree uint8_t *ciphertext = g_new0(uint8_t,
        count * PLAN9_AUTH_KEYDB_RECORD_LEN);
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);

    g_assert_cmpint(fd, >=, 0);
    for (size_t i = 0; i < count; i++) {
        uint8_t *record = ciphertext + i * PLAN9_AUTH_KEYDB_RECORD_LEN;
        size_t name_len = strnlen(records[i].name, PLAN9_AUTH_NAMELEN);
        Error *err = NULL;

        g_assert_cmpuint(name_len, <=, PLAN9_AUTH_NAMELEN);
        memcpy(record, records[i].name, name_len);
        memcpy(record + PLAN9_AUTH_NAMELEN, records[i].key,
               PLAN9_AUTH_DES_KEY_LEN);
        record[PLAN9_AUTH_NAMELEN + PLAN9_AUTH_DES_KEY_LEN] =
            records[i].status;
        record[PLAN9_AUTH_NAMELEN + PLAN9_AUTH_DES_KEY_LEN + 1] =
            records[i].warnings;
        stl_le_p(record + PLAN9_AUTH_NAMELEN + PLAN9_AUTH_DES_KEY_LEN + 2,
                 records[i].expiry);
        g_assert_cmpint(plan9_auth_encrypt(keydb_master_key, record,
                                            PLAN9_AUTH_KEYDB_RECORD_LEN,
                                            &err), ==, 0);
        g_assert_null(err);
    }
    g_assert_cmpint(write(fd, ciphertext,
                          count * PLAN9_AUTH_KEYDB_RECORD_LEN), ==,
                    count * PLAN9_AUTH_KEYDB_RECORD_LEN);
    close(fd);
    plan9_auth_clear(ciphertext, count * PLAN9_AUTH_KEYDB_RECORD_LEN);
}

static Plan9AuthKeydb *keydb_load(const char *path, const char *server,
                                   uint32_t now)
{
    Error *err = NULL;
    Plan9AuthKeydb *keydb = plan9_auth_keydb_load(path, keydb_master_key,
                                                   server, now, &err);

    g_assert_null(err);
    g_assert_nonnull(keydb);
    return keydb;
}

static void keydb_expect_rejected(const char *path, const char *server,
                                  uint32_t now)
{
    Error *err = NULL;

    g_assert_null(plan9_auth_keydb_load(path, keydb_master_key, server, now,
                                        &err));
    g_assert_nonnull(err);
    error_free(err);
}

static void test_keydb_golden_and_lookup(void)
{
    /*
     * Independently made with OpenSSL DES/ECB and the Second Edition
     * sys/man/2/encrypt overlap sequence at offsets 0,7,14,21,28,33, using
     * the historical 56-to-64 expansion of keydb_master_key.  This is one
     * native 41-byte /adm/keys record: p9fs, key 01..07, status ok, warning
     * 9, never expires.  It is deliberately not generated by the code under
     * test.
     */
    static const uint8_t golden[] = {
        0x75, 0x6f, 0x1a, 0x43, 0x45, 0x3a, 0x6d, 0xb7, 0xf1, 0x32,
        0x56, 0x77, 0x3c, 0x36, 0x05, 0xb9, 0x68, 0xaf, 0xca, 0xd1,
        0x57, 0x13, 0xa7, 0x3c, 0x8f, 0xab, 0xcf, 0x37, 0xd7, 0xd2,
        0x12, 0xeb, 0x03, 0xbd, 0x8d, 0x02, 0xe1, 0x88, 0x1c, 0x9f,
        0x2b,
    };
    static const KeydbFixtureRecord records[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 0, 9, 0 },
        { "tor", { 7, 6, 5, 4, 3, 2, 1 }, 0, 3, 100 },
        { "disabled", { 3, 3, 3, 3, 3, 3, 3 }, 1, 0, 0 },
        { "old", { 4, 4, 4, 4, 4, 4, 4 }, 0, 0, 99 },
    };
    g_autofree char *dir = keydb_tempdir();
    g_autofree char *path = g_build_filename(dir, "keys", NULL);
    uint8_t key[PLAN9_AUTH_DES_KEY_LEN] = { 0 };
    Plan9AuthKeydb *keydb;
    int fd;

    fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    g_assert_cmpint(fd, >=, 0);
    g_assert_cmpint(write(fd, golden, sizeof(golden)), ==, sizeof(golden));
    close(fd);
    keydb = keydb_load(path, "p9fs", 100);
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "p9fs", 100, key), ==,
                    PLAN9_AUTH_KEY_AVAILABLE);
    g_assert_cmpmem(key, sizeof(key), records[0].key, sizeof(key));
    plan9_auth_keydb_free(keydb);

    keydb_write(path, records, G_N_ELEMENTS(records));
    keydb = keydb_load(path, "p9fs", 100);
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "tor", 100, key), ==,
                    PLAN9_AUTH_KEY_AVAILABLE);
    g_assert_cmpmem(key, sizeof(key), records[1].key, sizeof(key));
    memset(key, 0xa5, sizeof(key));
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "disabled", 100, key),
                    ==, PLAN9_AUTH_KEY_DISABLED);
    assert_zeroed(key, sizeof(key));
    memset(key, 0xa5, sizeof(key));
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "old", 100, key), ==,
                    PLAN9_AUTH_KEY_EXPIRED);
    assert_zeroed(key, sizeof(key));
    memset(key, 0xa5, sizeof(key));
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "nope", 100, key), ==,
                    PLAN9_AUTH_KEY_MISSING);
    assert_zeroed(key, sizeof(key));
    plan9_auth_keydb_free(keydb);
    keydb_remove_tree(dir);
}

static void test_keydb_rejections(void)
{
    static const KeydbFixtureRecord valid[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 0, 0, 0 },
    };
    static const KeydbFixtureRecord duplicate[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 0, 0, 0 },
        { "p9fs", { 7, 6, 5, 4, 3, 2, 1 }, 0, 0, 0 },
    };
    static const KeydbFixtureRecord canonical_duplicate[] = {
        { "123456789012345678901234567a", { 1, 2, 3, 4, 5, 6, 7 },
          0, 0, 0 },
        { "123456789012345678901234567b", { 7, 6, 5, 4, 3, 2, 1 },
          0, 0, 0 },
    };
    static const KeydbFixtureRecord invalid[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 2, 0, 0 },
    };
    static const KeydbFixtureRecord disabled[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 1, 0, 0 },
    };
    static const KeydbFixtureRecord expired[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 0, 0, 99 },
    };
    g_autofree char *dir = keydb_tempdir();
    g_autofree char *path = g_build_filename(dir, "keys", NULL);
    int fd;

    fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    g_assert_cmpint(fd, >=, 0);
    close(fd);
    keydb_expect_rejected(path, "p9fs", 100);

    keydb_write(path, valid, 1);
    fd = open(path, O_WRONLY | O_APPEND);
    g_assert_cmpint(fd, >=, 0);
    g_assert_cmpint(write(fd, "x", 1), ==, 1);
    close(fd);
    keydb_expect_rejected(path, "p9fs", 100);

    keydb_write(path, duplicate, G_N_ELEMENTS(duplicate));
    keydb_expect_rejected(path, "p9fs", 100);
    keydb_write(path, canonical_duplicate, G_N_ELEMENTS(canonical_duplicate));
    keydb_expect_rejected(path, "123456789012345678901234567", 100);
    keydb_write(path, invalid, 1);
    keydb_expect_rejected(path, "p9fs", 100);
    keydb_write(path, disabled, 1);
    keydb_expect_rejected(path, "p9fs", 100);
    keydb_write(path, expired, 1);
    keydb_expect_rejected(path, "p9fs", 100);
    keydb_write(path, valid, 1);
    keydb_expect_rejected(path, "missing", 100);

    unlink(path);
    g_assert_cmpint(symlink("elsewhere", path), ==, 0);
    keydb_expect_rejected(path, "p9fs", 100);
    unlink(path);
    g_assert_cmpint(mkdir(path, 0700), ==, 0);
    keydb_expect_rejected(path, "p9fs", 100);
    rmdir(path);
    keydb_remove_tree(dir);
}

static void test_keydb_max_and_immutable_copy(void)
{
    KeydbFixtureRecord *records = g_new0(KeydbFixtureRecord,
                                         PLAN9_AUTH_KEYDB_MAX_RECORDS);
    g_autofree char *dir = keydb_tempdir();
    g_autofree char *path = g_build_filename(dir, "keys", NULL);
    Plan9AuthKeydb *keydb;
    uint8_t key[PLAN9_AUTH_DES_KEY_LEN];

    for (size_t i = 0; i < PLAN9_AUTH_KEYDB_MAX_RECORDS; i++) {
        records[i].name = g_strdup_printf("u%zu", i);
        memset(records[i].key, i, sizeof(records[i].key));
    }
    g_free((char *)records[0].name);
    records[0].name = "p9fs";
    keydb_write(path, records, PLAN9_AUTH_KEYDB_MAX_RECORDS);
    keydb = keydb_load(path, "p9fs", 0);
    unlink(path);
    g_assert_cmpint(plan9_auth_keydb_lookup(keydb, "u1", 0, key), ==,
                    PLAN9_AUTH_KEY_AVAILABLE);
    for (size_t i = 0; i < sizeof(key); i++) {
        g_assert_cmpuint(key[i], ==, 1);
    }
    plan9_auth_keydb_free(keydb);
    keydb_remove_tree(dir);
    for (size_t i = 1; i < PLAN9_AUTH_KEYDB_MAX_RECORDS; i++) {
        g_free((char *)records[i].name);
    }
    g_free(records);
}

static void test_keydb_over_limit(void)
{
    g_autofree char *dir = keydb_tempdir();
    g_autofree char *path = g_build_filename(dir, "keys", NULL);
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    uint8_t byte = 0;

    g_assert_cmpint(fd, >=, 0);
    g_assert_cmpint(lseek(fd, PLAN9_AUTH_KEYDB_RECORD_LEN *
                          PLAN9_AUTH_KEYDB_MAX_RECORDS, SEEK_SET), ==,
                    PLAN9_AUTH_KEYDB_RECORD_LEN * PLAN9_AUTH_KEYDB_MAX_RECORDS);
    g_assert_cmpint(write(fd, &byte, 1), ==, 1);
    close(fd);
    keydb_expect_rejected(path, "p9fs", 0);
    keydb_remove_tree(dir);
}

typedef struct KeydbRace {
    const char *path;
    const char *replacement;
} KeydbRace;

static void keydb_replace_after_read(const char *path, void *opaque)
{
    KeydbRace *race = opaque;

    g_assert_cmpstr(path, ==, race->path);
    g_assert_cmpint(rename(race->replacement, path), ==, 0);
}

static void test_keydb_changed_during_read(void)
{
    static const KeydbFixtureRecord original[] = {
        { "p9fs", { 1, 2, 3, 4, 5, 6, 7 }, 0, 0, 0 },
    };
    static const KeydbFixtureRecord replacement[] = {
        { "p9fs", { 7, 6, 5, 4, 3, 2, 1 }, 0, 0, 0 },
    };
    g_autofree char *dir = keydb_tempdir();
    g_autofree char *path = g_build_filename(dir, "keys", NULL);
    g_autofree char *replacement_path = g_build_filename(dir, "replacement",
                                                          NULL);
    KeydbRace race = { path, replacement_path };

    keydb_write(path, original, 1);
    keydb_write(replacement_path, replacement, 1);
    plan9_auth_keydb_set_read_hook(keydb_replace_after_read, &race);
    keydb_expect_rejected(path, "p9fs", 0);
    plan9_auth_keydb_set_read_hook(NULL, NULL);
    keydb_remove_tree(dir);
}

static void test_sizes(void)
{
    g_assert_cmpuint(PLAN9_AUTH_NAMELEN, ==, 28);
    g_assert_cmpuint(PLAN9_AUTH_DOMLEN, ==, 48);
    g_assert_cmpuint(PLAN9_AUTH_TICKET_REQUEST_LEN, ==, 141);
    g_assert_cmpuint(PLAN9_AUTH_TICKET_LEN, ==, 72);
    g_assert_cmpuint(PLAN9_AUTH_AUTHENTICATOR_LEN, ==, 13);
}

static void test_des56to64(void)
{
    static const uint8_t packed[PLAN9_AUTH_DES_KEY_LEN] = {
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
    };
    static const uint8_t expected[8] = {
        0x01, 0x91, 0xd0, 0xad, 0x79, 0x4c, 0xae, 0x9b,
    };
    uint8_t expanded[8];

    plan9_auth_des56to64(packed, expanded);
    g_assert_cmpmem(expanded, sizeof(expanded), expected, sizeof(expected));
}

static void test_passtokey(void)
{
    static const uint8_t short_expected[PLAN9_AUTH_DES_KEY_LEN] = {
        0x61, 0xf1, 0x18, 0x00, 0x02, 0x81, 0x40,
    };
    static const uint8_t long_expected[PLAN9_AUTH_DES_KEY_LEN] = {
        0x26, 0x1b, 0x62, 0xdb, 0x16, 0x3c, 0x49,
    };
    uint8_t key[PLAN9_AUTH_DES_KEY_LEN];
    static const char password_27[] = "012345678901234567890123456";
    static const char password_28[] = "0123456789012345678901234567";
    static const char password_utf8_27[] =
        "\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9"
        "\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9"
        "\xc3\xa9\xc3\xa9\xc3\xa9" "a";
    static const char password_utf8_28[] =
        "\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9"
        "\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9"
        "\xc3\xa9\xc3\xa9\xc3\xa9\xc3\xa9";
    Error *err = NULL;

    g_assert_cmpint(plan9_auth_passtokey(key, "", &err), ==, 0);
    g_assert_null(err);

    g_assert_cmpint(plan9_auth_passtokey(key, "abc", &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpmem(key, sizeof(key), short_expected, sizeof(short_expected));

    g_assert_cmpint(plan9_auth_passtokey(key, "123456789", &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpmem(key, sizeof(key), long_expected, sizeof(long_expected));

    g_assert_cmpuint(strlen(password_27), ==, PLAN9_AUTH_NAMELEN - 1);
    g_assert_cmpint(plan9_auth_passtokey(key, password_27, &err), ==, 0);
    g_assert_null(err);

    g_assert_cmpuint(strlen(password_28), ==, PLAN9_AUTH_NAMELEN);
    g_assert_cmpint(plan9_auth_passtokey(key, password_28, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    err = NULL;
    for (size_t i = 0; i < sizeof(key); i++) {
        g_assert_cmpuint(key[i], ==, 0);
    }

    g_assert_cmpuint(strlen(password_utf8_27), ==, PLAN9_AUTH_NAMELEN - 1);
    g_assert_cmpint(plan9_auth_passtokey(key, password_utf8_27, &err), ==, 0);
    g_assert_null(err);

    g_assert_cmpuint(strlen(password_utf8_28), ==, PLAN9_AUTH_NAMELEN);
    g_assert_cmpint(plan9_auth_passtokey(key, password_utf8_28, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    for (size_t i = 0; i < sizeof(key); i++) {
        g_assert_cmpuint(key[i], ==, 0);
    }
}

static void test_encrypt_vectors(void)
{
    static const uint8_t key[PLAN9_AUTH_DES_KEY_LEN] = {
        0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
    };
    static const uint8_t plain8[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
    static const uint8_t cipher8[] = {
        0x76, 0x3e, 0x78, 0xcf, 0xb5, 0x05, 0xed, 0xdd,
    };
    static const uint8_t cipher9[] = {
        0x76, 0x07, 0xa2, 0xbf, 0x54, 0x4c, 0x97, 0x1f, 0x1d,
    };
    static const uint8_t cipher14[] = {
        0x76, 0x3e, 0x78, 0xcf, 0xb5, 0x05, 0xd3,
        0x97, 0xa5, 0x76, 0xbe, 0x16, 0x81, 0xcd,
    };
    static const uint8_t cipher15[] = {
        0x76, 0x3e, 0x78, 0xcf, 0xb5, 0x05, 0xed, 0xd8,
        0x06, 0xdc, 0x3e, 0xb7, 0x81, 0xa4, 0x5c,
    };
    uint8_t buffer[sizeof(cipher15)];
    uint8_t wrong_key[PLAN9_AUTH_DES_KEY_LEN];
    Error *err = NULL;

    memcpy(buffer, plain8, sizeof(plain8));
    g_assert_cmpint(plan9_auth_encrypt(key, buffer, sizeof(plain8), &err),
                    ==, 0);
    g_assert_null(err);
    g_assert_cmpmem(buffer, sizeof(plain8), cipher8, sizeof(cipher8));
    g_assert_cmpint(plan9_auth_decrypt(key, buffer, sizeof(plain8), &err),
                    ==, 0);
    g_assert_null(err);
    g_assert_cmpmem(buffer, sizeof(plain8), plain8, sizeof(plain8));

    for (size_t len = 9; len <= sizeof(buffer); len++) {
        for (size_t i = 0; i < len; i++) {
            buffer[i] = i;
        }
        g_assert_cmpint(plan9_auth_encrypt(key, buffer, len, &err), ==, 0);
        g_assert_null(err);
        if (len == 9) {
            g_assert_cmpmem(buffer, len, cipher9, sizeof(cipher9));
        } else if (len == 14) {
            g_assert_cmpmem(buffer, len, cipher14, sizeof(cipher14));
        } else if (len == 15) {
            g_assert_cmpmem(buffer, len, cipher15, sizeof(cipher15));
        }
        g_assert_cmpint(plan9_auth_decrypt(key, buffer, len, &err), ==, 0);
        g_assert_null(err);
        for (size_t i = 0; i < len; i++) {
            g_assert_cmpuint(buffer[i], ==, i);
        }
    }

    g_assert_cmpint(plan9_auth_encrypt(key, buffer, 7, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    err = NULL;

    memcpy(buffer, cipher8, sizeof(cipher8));
    memcpy(wrong_key, key, sizeof(wrong_key));
    wrong_key[0] ^= 0x80;
    g_assert_cmpint(plan9_auth_decrypt(wrong_key, buffer, sizeof(cipher8),
                                       &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpint(memcmp(buffer, plain8, sizeof(plain8)), !=, 0);
}

static void test_ticket_request_codec(void)
{
    Plan9AuthTicketRequest request = {
        .type = PLAN9_AUTH_TREQ,
        .authid = "p9fs",
        .authdom = "nextlab",
        .challenge = { 1, 2, 3, 4, 5, 6, 7, 8 },
        .hostid = "tor",
        .uid = "tor",
    };
    Plan9AuthTicketRequest decoded;
    uint8_t wire[PLAN9_AUTH_TICKET_REQUEST_LEN];
    Error *err = NULL;

    g_assert_cmpint(plan9_auth_ticket_request_encode(&request, wire, &err),
                    ==, 0);
    g_assert_null(err);
    g_assert_cmpuint(wire[0], ==, PLAN9_AUTH_TREQ);
    g_assert_cmpmem(wire + 1, 4, "p9fs", 4);
    g_assert_cmpmem(wire + 29, 7, "nextlab", 7);
    g_assert_cmpmem(wire + 77, 8, request.challenge, 8);
    g_assert_cmpmem(wire + 85, 3, "tor", 3);
    g_assert_cmpmem(wire + 113, 3, "tor", 3);
    g_assert_cmpint(plan9_auth_ticket_request_decode(wire, sizeof(wire),
                                                      &decoded, &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpuint(decoded.type, ==, request.type);
    g_assert_cmpstr(decoded.authid, ==, request.authid);
    g_assert_cmpstr(decoded.authdom, ==, request.authdom);
    g_assert_cmpmem(decoded.challenge, sizeof(decoded.challenge),
                    request.challenge, sizeof(request.challenge));

    request.uid[0] = 'x';
    memset(request.uid + 1, 'x', PLAN9_AUTH_NAMELEN - 1);
    g_assert_cmpint(plan9_auth_ticket_request_encode(&request, wire, &err),
                    <, 0);
    g_assert_nonnull(err);
    error_free(err);
}

static void test_ticket_and_authenticator_codecs(void)
{
    Plan9AuthTicket ticket = {
        .num = PLAN9_AUTH_TC,
        .challenge = { 8, 7, 6, 5, 4, 3, 2, 1 },
        .cuid = "tor",
        .suid = "p9fs",
        .key = { 1, 2, 3, 4, 5, 6, 7 },
    };
    Plan9AuthTicket ticket_decoded;
    Plan9AuthAuthenticator auth = {
        .num = PLAN9_AUTH_AC,
        .challenge = { 1, 3, 3, 7, 0, 0, 0, 1 },
        .id = 0x78563412,
    };
    Plan9AuthAuthenticator auth_decoded;
    uint8_t ticket_wire[PLAN9_AUTH_TICKET_LEN];
    uint8_t auth_wire[PLAN9_AUTH_AUTHENTICATOR_LEN];
    Error *err = NULL;

    g_assert_cmpint(plan9_auth_ticket_encode(&ticket, ticket_wire, &err),
                    ==, 0);
    g_assert_null(err);
    g_assert_cmpuint(ticket_wire[0], ==, PLAN9_AUTH_TC);
    g_assert_cmpmem(ticket_wire + 1, 8, ticket.challenge, 8);
    g_assert_cmpmem(ticket_wire + 9, 3, "tor", 3);
    g_assert_cmpmem(ticket_wire + 37, 4, "p9fs", 4);
    g_assert_cmpmem(ticket_wire + 65, 7, ticket.key, 7);
    g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire, sizeof(ticket_wire),
                                              &ticket_decoded, &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpstr(ticket_decoded.cuid, ==, ticket.cuid);
    g_assert_cmpstr(ticket_decoded.suid, ==, ticket.suid);
    g_assert_cmpmem(ticket_decoded.key, sizeof(ticket_decoded.key),
                    ticket.key, sizeof(ticket.key));

    g_assert_cmpint(plan9_auth_authenticator_encode(&auth, auth_wire, &err),
                    ==, 0);
    g_assert_null(err);
    g_assert_cmpuint(auth_wire[0], ==, PLAN9_AUTH_AC);
    g_assert_cmpmem(auth_wire + 1, 8, auth.challenge, 8);
    g_assert_cmpmem(auth_wire + 9, 4, "\x12\x34\x56\x78", 4);
    g_assert_cmpint(plan9_auth_authenticator_decode(auth_wire,
                                                     sizeof(auth_wire),
                                                     &auth_decoded,
                                                     &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpuint(auth_decoded.id, ==, auth.id);

    g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire,
                                              sizeof(ticket_wire) - 1,
                                              &ticket_decoded, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
}

static void test_rejections_wipe_ticket_output(void)
{
    Plan9AuthTicket ticket = {
        .num = PLAN9_AUTH_TC,
        .challenge = { 8, 7, 6, 5, 4, 3, 2, 1 },
        .suid = "p9fs",
        .key = { 1, 2, 3, 4, 5, 6, 7 },
    };
    uint8_t wire[PLAN9_AUTH_TICKET_LEN];
    Error *err = NULL;

    memset(ticket.cuid, 'x', PLAN9_AUTH_NAMELEN);
    memset(wire, 0xa5, sizeof(wire));
    g_assert_cmpint(plan9_auth_ticket_encode(&ticket, wire, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    for (size_t i = 0; i < sizeof(wire); i++) {
        g_assert_cmpuint(wire[i], ==, 0);
    }
}

static void test_invalid_arguments(void)
{
    Error *err = NULL;

    g_assert_cmpint(plan9_auth_passtokey(NULL, "abc", &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    err = NULL;
    g_assert_cmpint(plan9_auth_ticket_decode(NULL, PLAN9_AUTH_TICKET_LEN,
                                             NULL, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
}

static void assert_zeroed(const void *data, size_t len)
{
    const uint8_t *bytes = data;

    for (size_t i = 0; i < len; i++) {
        g_assert_cmpuint(bytes[i], ==, 0);
    }
}

static void test_public_clear(void)
{
    uint8_t plaintext[PLAN9_AUTH_TICKET_LEN];
    Plan9AuthTicket ticket;

    memset(plaintext, 0xa5, sizeof(plaintext));
    plan9_auth_clear(plaintext, sizeof(plaintext));
    assert_zeroed(plaintext, sizeof(plaintext));

    memset(&ticket, 0xa5, sizeof(ticket));
    plan9_auth_ticket_clear(&ticket);
    assert_zeroed(&ticket, sizeof(ticket));
}

static void test_encode_failure_wipes_output(void)
{
    Plan9AuthTicketRequest request = {
        .authid = "p9fs",
        .authdom = "nextlab",
        .hostid = "tor",
        .uid = "tor",
    };
    Plan9AuthTicket ticket = {
        .cuid = "tor",
        .suid = "p9fs",
        .key = { 1, 2, 3, 4, 5, 6, 7 },
    };
    Plan9AuthAuthenticator auth = { 0 };
    uint8_t request_wire[PLAN9_AUTH_TICKET_REQUEST_LEN];
    uint8_t ticket_wire[PLAN9_AUTH_TICKET_LEN];
    uint8_t auth_wire[PLAN9_AUTH_AUTHENTICATOR_LEN];
    Error *err = NULL;

    memset(request_wire, 0xa5, sizeof(request_wire));
    g_assert_cmpint(plan9_auth_ticket_request_encode(NULL, request_wire, &err),
                    <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(request_wire, sizeof(request_wire));
    err = NULL;

    memset(request.authid, 'x', PLAN9_AUTH_NAMELEN);
    memset(request_wire, 0xa5, sizeof(request_wire));
    g_assert_cmpint(plan9_auth_ticket_request_encode(&request, request_wire,
                                                      &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(request_wire, sizeof(request_wire));
    err = NULL;

    memset(ticket_wire, 0xa5, sizeof(ticket_wire));
    g_assert_cmpint(plan9_auth_ticket_encode(NULL, ticket_wire, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(ticket_wire, sizeof(ticket_wire));
    err = NULL;

    memset(auth_wire, 0xa5, sizeof(auth_wire));
    g_assert_cmpint(plan9_auth_authenticator_encode(NULL, auth_wire, &err),
                    <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(auth_wire, sizeof(auth_wire));
    err = NULL;

    g_assert_cmpint(plan9_auth_ticket_request_encode(&request, NULL, &err),
                    <, 0);
    g_assert_nonnull(err);
    error_free(err);
    err = NULL;
    g_assert_cmpint(plan9_auth_ticket_encode(&ticket, NULL, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    err = NULL;
    g_assert_cmpint(plan9_auth_authenticator_encode(&auth, NULL, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
}

static void test_decode_failure_wipes_destination(void)
{
    uint8_t request_wire[PLAN9_AUTH_TICKET_REQUEST_LEN] = { 0 };
    uint8_t ticket_wire[PLAN9_AUTH_TICKET_LEN] = { 0 };
    uint8_t auth_wire[PLAN9_AUTH_AUTHENTICATOR_LEN] = { 0 };
    Plan9AuthTicketRequest request;
    Plan9AuthTicket ticket;
    Plan9AuthAuthenticator auth;
    Error *err = NULL;

    memset(&request, 0xa5, sizeof(request));
    g_assert_cmpint(plan9_auth_ticket_request_decode(NULL, sizeof(request_wire),
                                                      &request, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&request, sizeof(request));
    err = NULL;

    memset(&request, 0xa5, sizeof(request));
    g_assert_cmpint(plan9_auth_ticket_request_decode(request_wire,
                                                      sizeof(request_wire) - 1,
                                                      &request, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&request, sizeof(request));
    err = NULL;

    memset(&request, 0xa5, sizeof(request));
    g_assert_cmpint(plan9_auth_ticket_request_decode(request_wire,
                                                      sizeof(request_wire) + 1,
                                                      &request, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&request, sizeof(request));
    err = NULL;

    memset(&ticket, 0xa5, sizeof(ticket));
    g_assert_cmpint(plan9_auth_ticket_decode(NULL, sizeof(ticket_wire),
                                              &ticket, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&ticket, sizeof(ticket));
    err = NULL;

    memset(&ticket, 0xa5, sizeof(ticket));
    g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire,
                                              sizeof(ticket_wire) - 1,
                                              &ticket, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&ticket, sizeof(ticket));
    err = NULL;

    memset(&ticket, 0xa5, sizeof(ticket));
    g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire,
                                              sizeof(ticket_wire) + 1,
                                              &ticket, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&ticket, sizeof(ticket));
    err = NULL;

    memset(&auth, 0xa5, sizeof(auth));
    g_assert_cmpint(plan9_auth_authenticator_decode(NULL, sizeof(auth_wire),
                                                     &auth, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&auth, sizeof(auth));
    err = NULL;

    memset(&auth, 0xa5, sizeof(auth));
    g_assert_cmpint(plan9_auth_authenticator_decode(auth_wire,
                                                     sizeof(auth_wire) - 1,
                                                     &auth, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&auth, sizeof(auth));
    err = NULL;

    memset(&auth, 0xa5, sizeof(auth));
    g_assert_cmpint(plan9_auth_authenticator_decode(auth_wire,
                                                     sizeof(auth_wire) + 1,
                                                     &auth, &err), <, 0);
    g_assert_nonnull(err);
    error_free(err);
    assert_zeroed(&auth, sizeof(auth));
}

static void test_decode_fixed_string_compatibility(void)
{
    uint8_t request_wire[PLAN9_AUTH_TICKET_REQUEST_LEN] = { 0 };
    uint8_t ticket_wire[PLAN9_AUTH_TICKET_LEN] = { 0 };
    Plan9AuthTicketRequest request;
    Plan9AuthTicket ticket;
    Error *err = NULL;
    const size_t request_fields[] = { 1, 29, 85, 113 };
    const size_t request_sizes[] = {
        PLAN9_AUTH_NAMELEN, PLAN9_AUTH_DOMLEN,
        PLAN9_AUTH_NAMELEN, PLAN9_AUTH_NAMELEN,
    };
    const size_t ticket_fields[] = { 9, 37 };

    for (size_t i = 0; i < G_N_ELEMENTS(request_fields); i++) {
        memset(request_wire, 0, sizeof(request_wire));
        memset(request_wire + request_fields[i], 'x', request_sizes[i]);
        char *const dest[] = {
            request.authid, request.authdom, request.hostid, request.uid,
        };

        memset(&request, 0xa5, sizeof(request));
        g_assert_cmpint(plan9_auth_ticket_request_decode(request_wire,
                                                          sizeof(request_wire),
                                                          &request, &err),
                        ==, 0);
        g_assert_null(err);
        g_assert_cmpuint(dest[i][request_sizes[i] - 2], ==, 'x');
        g_assert_cmpuint(dest[i][request_sizes[i] - 1], ==, 0);
        g_assert_cmpuint(dest[i][request_sizes[i]], ==, 0);
    }

    for (size_t i = 0; i < G_N_ELEMENTS(ticket_fields); i++) {
        memset(ticket_wire, 0, sizeof(ticket_wire));
        memset(ticket_wire + ticket_fields[i], 'x', PLAN9_AUTH_NAMELEN);
        char *const dest[] = { ticket.cuid, ticket.suid };

        memset(&ticket, 0xa5, sizeof(ticket));
        g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire,
                                                  sizeof(ticket_wire),
                                                  &ticket, &err), ==, 0);
        g_assert_null(err);
        g_assert_cmpuint(dest[i][PLAN9_AUTH_NAMELEN - 2], ==, 'x');
        g_assert_cmpuint(dest[i][PLAN9_AUTH_NAMELEN - 1], ==, 0);
        g_assert_cmpuint(dest[i][PLAN9_AUTH_NAMELEN], ==, 0);
    }

    memset(request_wire, 0, sizeof(request_wire));
    request_wire[1] = 'a';
    request_wire[2] = 0;
    request_wire[3] = 0xa5;
    request_wire[29] = 'd';
    request_wire[30] = 0;
    request_wire[31] = 0xa5;
    request_wire[85] = 'h';
    request_wire[86] = 0;
    request_wire[87] = 0xa5;
    request_wire[113] = 'u';
    request_wire[114] = 0;
    request_wire[115] = 0xa5;
    g_assert_cmpint(plan9_auth_ticket_request_decode(request_wire,
                                                      sizeof(request_wire),
                                                      &request, &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpstr(request.authid, ==, "a");
    g_assert_cmpstr(request.authdom, ==, "d");
    g_assert_cmpstr(request.hostid, ==, "h");
    g_assert_cmpstr(request.uid, ==, "u");
    g_assert_cmpuint((uint8_t)request.authid[2], ==, 0xa5);
    g_assert_cmpuint((uint8_t)request.authdom[2], ==, 0xa5);
    g_assert_cmpuint((uint8_t)request.hostid[2], ==, 0xa5);
    g_assert_cmpuint((uint8_t)request.uid[2], ==, 0xa5);

    memset(ticket_wire, 0, sizeof(ticket_wire));
    ticket_wire[9] = 'c';
    ticket_wire[10] = 0;
    ticket_wire[11] = 0xa5;
    ticket_wire[37] = 's';
    ticket_wire[38] = 0;
    ticket_wire[39] = 0xa5;
    g_assert_cmpint(plan9_auth_ticket_decode(ticket_wire, sizeof(ticket_wire),
                                              &ticket, &err), ==, 0);
    g_assert_null(err);
    g_assert_cmpstr(ticket.cuid, ==, "c");
    g_assert_cmpstr(ticket.suid, ==, "s");
    g_assert_cmpuint((uint8_t)ticket.cuid[2], ==, 0xa5);
    g_assert_cmpuint((uint8_t)ticket.suid[2], ==, 0xa5);
    plan9_auth_ticket_clear(&ticket);
    assert_zeroed(&ticket, sizeof(ticket));
}

int main(int argc, char **argv)
{
    g_test_init(&argc, &argv, NULL);
    g_test_add_func("/plan9-auth/sizes", test_sizes);
    g_test_add_func("/plan9-auth/des56to64", test_des56to64);
    g_test_add_func("/plan9-auth/passtokey", test_passtokey);
    g_test_add_func("/plan9-auth/encrypt", test_encrypt_vectors);
    g_test_add_func("/plan9-auth/ticket-request", test_ticket_request_codec);
    g_test_add_func("/plan9-auth/ticket-authenticator",
                    test_ticket_and_authenticator_codecs);
    g_test_add_func("/plan9-auth/rejections-wipe-ticket-output",
                    test_rejections_wipe_ticket_output);
    g_test_add_func("/plan9-auth/invalid-arguments", test_invalid_arguments);
    g_test_add_func("/plan9-auth/public-clear", test_public_clear);
    g_test_add_func("/plan9-auth/encode-failure-wipes-output",
                    test_encode_failure_wipes_output);
    g_test_add_func("/plan9-auth/decode-failure-wipes-destination",
                    test_decode_failure_wipes_destination);
    g_test_add_func("/plan9-auth/decode-fixed-string-compatibility",
                    test_decode_fixed_string_compatibility);
    g_test_add_func("/plan9-auth/keydb-golden-and-lookup",
                    test_keydb_golden_and_lookup);
    g_test_add_func("/plan9-auth/keydb-rejections", test_keydb_rejections);
    g_test_add_func("/plan9-auth/keydb-max-and-immutable-copy",
                    test_keydb_max_and_immutable_copy);
    g_test_add_func("/plan9-auth/keydb-over-limit", test_keydb_over_limit);
    g_test_add_func("/plan9-auth/keydb-changed-during-read",
                    test_keydb_changed_during_read);
    return g_test_run();
}
